<Project>
  <PropertyGroup>
    <IntDir>$(SolutionDir)Build\$(Configuration)\$(MSBuildProjectName)\Intermediate\</IntDir>
    <OutDir>$(SolutionDir)Build\$(Configuration)\$(MSBuildProjectName)\</OutDir>
    <ProgramDataBaseFileName>$(IntDir)$(MSBuildProjectName).pdb</ProgramDataBaseFileName>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <!-- disable PDB generation -->
      <DebugInformationFormat>None</DebugInformationFormat>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>