name: Build HIP VS

on:
  push:
    branches: [ amd-staging, amd-mainline, release/** ]
  pull_request:
    branches: [ amd-staging, amd-mainline, release/** ]

env:
    ROCM_VERSION: 6.4
    HIPSDK_INSTALLER_VERSION: 24.Q4
    GPU_TARGETS: gfx803;gfx900;gfx906;gfx908;gfx90a;gfx942;gfx1030;gfx1100;gfx1101;gfx1102;gfx1201

jobs:
    build:
        name: "Build Examples"
        runs-on: windows-latest
        steps:
          - uses: actions/checkout@v4
          - uses: microsoft/setup-msbuild@v2
          - name: Install HIP SDK
            shell: pwsh
            run: |
                  Invoke-WebRequest -Uri https://download.amd.com/developer/eula/rocm-hub/AMD-Software-PRO-Edition-${{ env.HIPSDK_INSTALLER_VERSION }}-Win10-Win11-For-HIP.exe -OutFile Setup.exe
                  Start-Process Setup.exe -ArgumentList '-install','-log',"installer_log.txt" -NoNewWindow -Wait
                  ls "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Platforms\x64\PlatformToolsets\"
                  msbuild -ver
