# name: Build HIP VS

# on:
#   push:
#     branches: [ amd-staging, amd-mainline, release/**, windows-ci ]
#   pull_request:
#     branches: [ amd-staging, amd-mainline, release/** ]

# env:
#     PLATFORM_TOOLSET_VERSION: 6.2
#     HIP_PATH: C:\Program Files\AMD\ROCm\6.2\
#     HIPSDK_INSTALLER_VERSION: 24.Q4

# jobs:
#     build:
#         name: "Build Examples"
#         runs-on: windows-latest
#         steps:
#           - uses: actions/checkout@v4
#           - uses: microsoft/setup-msbuild@v2
#           - name: Install HIP SDK
#             shell: pwsh
#             run: |
#                   $ProgressPreference = 'SilentlyContinue'
#                   Invoke-WebRequest -Uri https://download.amd.com/developer/eula/rocm-hub/AMD-Software-PRO-Edition-${{ env.HIPSDK_INSTALLER_VERSION }}-Win10-Win11-For-HIP.exe -OutFile Setup.exe
#                   Start-Process Setup.exe -ArgumentList '-install','-log',"installer_log.txt" -NoNewWindow -Wait
#                   echo $env:HIP_PATH
#                   msbuild -ver
#           - name: Install dependencies
#             shell: pwsh
#             run: |
#                   python3 -m pip install rich
#           - name: Check GUID
#             shell: pwsh
#             run: |
#                   python3 Scripts/VisualStudio/check_vs_files.py
#           - name: Build Debug x64
#             shell: pwsh
#             run: |
#                   .\Scripts\VisualStudio\build.ps1 -Config Debug
                  
#           #         msbuild -maxCpuCount -detailedSummary -property:"Configuration=Debug;Platform=x64" ROCm-Examples-VS2022.sln
#           - name: Build Release x64
#             shell: pwsh
#             run: |
#                   .\Scripts\VisualStudio\build.ps1 -Config Release
#           # - name: Build Portable
#           #   shell: pwsh
#           #   run: |
#           #         msbuild -maxCpuCount -detailedSummary -property:Configuration=Debug;Platform=x64;PlatformToolset="HIP nvcc ${{ env.PLATFORM_TOOLSET_VERSION }}" ROCm-Examples-VS2017.sln
          
#           #  Get-ChildItem -Path . -Recurse -Filter "*.sln"  -Name  -Exclude @("vulkan_interop*", "ROCm-Examples*")
